
const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
const FETCH_DATA         = 'FETCH_DATA'
const FETCH_DATA_ERROR   = 'FETCH_DATA_ERROR'
const MOVE_ITEM          = 'MOVE_ITEM'

export default {
    FETCH_DATA_SUCCESS,
    FETCH_DATA,
    FETCH_DATA_ERROR,
    MOVE_ITEM
}